server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
